x-global-env: &global-env
  JWT_SECRET: "UF/4GCdTitbUiCB/+YuCFFN6OYkZKthe1XQD3gSfBF4="
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "root"
  DB_PASSWORD: "root"
  DB_NAME: "finn_tracker"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - user-service
      - expense-service
      
  user-service:
    build:
      context: ./user_service
    container_name: user-service
    environment:
      <<: *global-env
    ports:
      - "5003:5003"
    networks:
      - app-network
    depends_on:
      - postgres
    command: /wait-for-it.sh postgres:5432 -- /app/user-service

  expense-service:
    build: 
      context: ./expense_service
    container_name: expense-service
    environment:
      <<: *global-env
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      - postgres

  stock-service:
    build: 
      context: ./stock
    container_name: stock-service
    ports:
      - "7001:7001"
    networks:
      - app-network
      
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: finn_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
